/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSpeakersRouteImport } from './routes/_authenticated/admin.speakers'
import { Route as AuthenticatedAdminSectionsRouteImport } from './routes/_authenticated/admin.sections'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated/admin.registrations'
import { Route as AuthenticatedAdminRegisterPageRouteImport } from './routes/_authenticated/admin.register-page'
import { Route as AuthenticatedAdminProgramRouteImport } from './routes/_authenticated/admin.program'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminParticipantsRouteImport } from './routes/_authenticated/admin.participants'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin.hero'
import { Route as AuthenticatedAdminFooterRouteImport } from './routes/_authenticated/admin.footer'
import { Route as AuthenticatedAdminEmailSettingsRouteImport } from './routes/_authenticated/admin.email-settings'
import { Route as AuthenticatedAdminCheckinRouteImport } from './routes/_authenticated/admin.checkin'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'

const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSpeakersRoute =
  AuthenticatedAdminSpeakersRouteImport.update({
    id: '/speakers',
    path: '/speakers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSectionsRoute =
  AuthenticatedAdminSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegisterPageRoute =
  AuthenticatedAdminRegisterPageRouteImport.update({
    id: '/register-page',
    path: '/register-page',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramRoute =
  AuthenticatedAdminProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParticipantsRoute =
  AuthenticatedAdminParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFooterRoute =
  AuthenticatedAdminFooterRouteImport.update({
    id: '/footer',
    path: '/footer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailSettingsRoute =
  AuthenticatedAdminEmailSettingsRouteImport.update({
    id: '/email-settings',
    path: '/email-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCheckinRoute =
  AuthenticatedAdminCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/setup-admin': typeof SetupAdminRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/email-settings': typeof AuthenticatedAdminEmailSettingsRoute
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/participants': typeof AuthenticatedAdminParticipantsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/program': typeof AuthenticatedAdminProgramRoute
  '/admin/register-page': typeof AuthenticatedAdminRegisterPageRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/speakers': typeof AuthenticatedAdminSpeakersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/setup-admin': typeof SetupAdminRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/email-settings': typeof AuthenticatedAdminEmailSettingsRoute
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/participants': typeof AuthenticatedAdminParticipantsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/program': typeof AuthenticatedAdminProgramRoute
  '/admin/register-page': typeof AuthenticatedAdminRegisterPageRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/speakers': typeof AuthenticatedAdminSpeakersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/setup-admin': typeof SetupAdminRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/_authenticated/admin/email-settings': typeof AuthenticatedAdminEmailSettingsRoute
  '/_authenticated/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/participants': typeof AuthenticatedAdminParticipantsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/program': typeof AuthenticatedAdminProgramRoute
  '/_authenticated/admin/register-page': typeof AuthenticatedAdminRegisterPageRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/_authenticated/admin/speakers': typeof AuthenticatedAdminSpeakersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/register'
    | '/setup-admin'
    | '/admin'
    | '/admin/about'
    | '/admin/checkin'
    | '/admin/email-settings'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/participants'
    | '/admin/partners'
    | '/admin/program'
    | '/admin/register-page'
    | '/admin/registrations'
    | '/admin/sections'
    | '/admin/speakers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/setup-admin'
    | '/admin/about'
    | '/admin/checkin'
    | '/admin/email-settings'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/participants'
    | '/admin/partners'
    | '/admin/program'
    | '/admin/register-page'
    | '/admin/registrations'
    | '/admin/sections'
    | '/admin/speakers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/register'
    | '/setup-admin'
    | '/_authenticated/admin'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/checkin'
    | '/_authenticated/admin/email-settings'
    | '/_authenticated/admin/footer'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/participants'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/program'
    | '/_authenticated/admin/register-page'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/sections'
    | '/_authenticated/admin/speakers'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegisterRoute: typeof RegisterRoute
  SetupAdminRoute: typeof SetupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/speakers': {
      id: '/_authenticated/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AuthenticatedAdminSpeakersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sections': {
      id: '/_authenticated/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AuthenticatedAdminSectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/register-page': {
      id: '/_authenticated/admin/register-page'
      path: '/register-page'
      fullPath: '/admin/register-page'
      preLoaderRoute: typeof AuthenticatedAdminRegisterPageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/program': {
      id: '/_authenticated/admin/program'
      path: '/program'
      fullPath: '/admin/program'
      preLoaderRoute: typeof AuthenticatedAdminProgramRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/participants': {
      id: '/_authenticated/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AuthenticatedAdminParticipantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/footer': {
      id: '/_authenticated/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AuthenticatedAdminFooterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-settings': {
      id: '/_authenticated/admin/email-settings'
      path: '/email-settings'
      fullPath: '/admin/email-settings'
      preLoaderRoute: typeof AuthenticatedAdminEmailSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/checkin': {
      id: '/_authenticated/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AuthenticatedAdminCheckinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminCheckinRoute: typeof AuthenticatedAdminCheckinRoute
  AuthenticatedAdminEmailSettingsRoute: typeof AuthenticatedAdminEmailSettingsRoute
  AuthenticatedAdminFooterRoute: typeof AuthenticatedAdminFooterRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminParticipantsRoute: typeof AuthenticatedAdminParticipantsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminProgramRoute: typeof AuthenticatedAdminProgramRoute
  AuthenticatedAdminRegisterPageRoute: typeof AuthenticatedAdminRegisterPageRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminSectionsRoute: typeof AuthenticatedAdminSectionsRoute
  AuthenticatedAdminSpeakersRoute: typeof AuthenticatedAdminSpeakersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminCheckinRoute: AuthenticatedAdminCheckinRoute,
  AuthenticatedAdminEmailSettingsRoute: AuthenticatedAdminEmailSettingsRoute,
  AuthenticatedAdminFooterRoute: AuthenticatedAdminFooterRoute,
  AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
  AuthenticatedAdminParticipantsRoute: AuthenticatedAdminParticipantsRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminProgramRoute: AuthenticatedAdminProgramRoute,
  AuthenticatedAdminRegisterPageRoute: AuthenticatedAdminRegisterPageRoute,
  AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
  AuthenticatedAdminSectionsRoute: AuthenticatedAdminSectionsRoute,
  AuthenticatedAdminSpeakersRoute: AuthenticatedAdminSpeakersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
  SetupAdminRoute: SetupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
